---
- name: install libvirt items
  become: true
  ansible.builtin.apt:
    name: "{{ libvirt_packages | union(additional_libvirt_packages | default([])) | unique }}"
    state: latest
  tags:
    - kvm
    - libvirt

# TODO: this line should probably be more dynamic
- name: Enable bridge networking for libvirt
  block:
    - name: create /etc/qemu/bridge.conf
      become: true
      ansible.builtin.lineinfile:
        path: /etc/qemu/bridge.conf
        line: 'allow virbr0'
        create: true
        mode: 0644

    - name: ensure setuid bit is set on /usr/lib/qemu/qemu-bridge-helper
      become: true
      ansible.builtin.file:
        path: /usr/lib/qemu/qemu-bridge-helper
        mode: u+s
  when: libvirt_enable_bridge
