---
# Defaults that can be override per-host

# common role
configure_complete_alias: true

configure_vagrant: false

configure_docker: false
configure_podman: false

configure_gaming: false
configure_gamehub: false

configure_kvm: false

desktop_dark_mode: false
