---
# Defaults that can be override per-host

# common role
configure_complete_alias: true

configure_container_management: false

configure_gaming: false
configure_gamehub: false

configure_virtualization: false

configure_vscode: false
