---
- hosts: all
  gather_facts: true
  vars_files:
    - default.config.yml
  pre_tasks:
  - name: Include host-specific configuration
    ansible.builtin.include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}.yml"
    tags: [always]

  roles:
    - common
    - desktop
    - peripherals
    - {role: chat_clients, tags: ['chat_clients']}
    - {role: gaming, tags: ['gaming'], when: configure_gaming}
    - {role: web_browsers, tags: ['web_browsers']}
    - {role: kvm, tags: ['kvm', 'libvirt'], when: configure_kvm}
