---
- hosts: all
  gather_facts: true
  pre_tasks:
  - name: Include host-specific configuration
    include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/hostname_vars/{{ ansible_hostname }}.yml"
      - "{{ playbook_dir }}/config.yml"
    tags: [always]

  roles:
    - common
    - gaming
    - peripherals
    - {role: chat-clients, tags: ['chat-clients']}
    - {role: web-browsers, tags: ['web-browsers']}
