---
- hosts: all
  gather_facts: true
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include host-specific configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}.yml"
      tags: [always]

  roles:
    - package_management
    - common
    - development
    - desktop
    - peripherals
    - {role: chat_clients, tags: ['chat_clients']}
    - {role: gaming, tags: ['gaming'], when: configure_gaming}
    - {role: web_browsers, tags: ['web_browsers']}
    - {role: virtualization, tags: ['virtualization'], when: configure_virtualization}
    - {role: vscode, tags: ['vscode'], when: configure_vscode}
