---
- hosts: all
  gather_facts: true
  pre_tasks:
  - name: Include host-specific configuration
    include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/hostname_vars/{{ ansible_hostname }}.yml"
      - "{{ playbook_dir }}/config.yml"
    tags: [always]

  roles:
    - common
    - desktop
    - peripherals
    - {role: chat_clients, tags: ['chat_clients']}
    - {role: gaming, tags: ['gaming'], when: enable_gaming is defined and enable_gaming}
    - {role: web_browsers, tags: ['web_browsers']}
