---
# For WSL and other non-full personal entities
- hosts: all
  gather_facts: true
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include host-specific configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}.yml"
      tags: [always]

  roles:
    - common
    - development
