---
- name: verify a valid release channel is specified
  ansible.builtin.assert:
    that:
      - google_chrome_release_channel in google_chrome_valid_release_channels
    fail_msg: "google_chrome_release_channel needs to be one of {{ google_chrome_valid_release_channels }}"

- name: include OS-specific native installation tasks
  ansible.builtin.include_tasks: "chrome-{{ ansible_facts['os_family'] }}.yml"

- name: create a dark mode desktop entry
  ansible.builtin.template:
    src: google-chrome.desktop.j2
    dest: "{{ ansible_user_dir }}/.local/share/applications/google-chrome.desktop"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775
  when: google_chrome_dark_mode
