---
- name: include os-specific variables
  include_vars: "google-chrome-{{ ansible_os_family }}.yml"

- name: define google_chrome_package
  set_fact:
    google_chrome_package: "{{ __google_chrome_package }}"
  when: google_chrome_package is not defined

- name: check google chrome version is installed
  command: "dpkg-query -W {{ google_chrome_package_name }}"
  register: _google_chrome_installed_version
  changed_when: false
  check_mode: false
  failed_when: false

- name: set decision to install google chrome
  set_fact:
    google_chrome_install: "{{ _google_chrome_installed_version.rc == 1 }}"

- name: download google chrome package
  get_url:
    url: "{{ google_chrome_download_url }}/{{ google_chrome_package }}"
    dest: /tmp/
  when: google_chrome_install

- name: install google chrome package
  become: true
  apt:
    deb: "/tmp/{{ google_chrome_package }}"
    state: present
  when: google_chrome_install

- name: cleanup google chrome package download
  file:
    dest: "/tmp/{{ google_chrome_package }}"
    state: absent
