---
# early refactor thought: i wonder if all these blocks are going to be the same and could/should just be looped through...
- name: configure discord
  when: "'discord' in communication_clients"
  tags:
    - discord
  block:
    - name: include OS-specific native installation tasks
      when: discord_installation_method in ['native', 'dnf', 'rpm', 'apt', 'deb']
      ansible.builtin.include_tasks: "discord/{{ ansible_facts['os_family'] }}.yml"

    - name: include flatpak installation tasks
      when: discord_installation_method == 'flatpak'
      ansible.builtin.import_tasks: discord/flatpak.yml

- name: configure signal
  when: "'signal' in communication_clients"
  tags:
    - signal
  block:
    - name: include OS-specific native installation tasks
      when: signal_installation_method in ['native', 'dnf', 'rpm', 'apt', 'deb']
      ansible.builtin.include_tasks: "signal/{{ ansible_facts['os_family'] }}.yml"

    - name: include flatpak installation tasks
      when: signal_installation_method == 'flatpak'
      ansible.builtin.import_tasks: signal/flatpak.yml

- name: configure slack
  when: "'slack' in communication_clients"
  tags:
    - slack
  block:
    - name: include OS-specific native installation tasks
      when: slack_installation_method in ['native', 'dnf', 'rpm', 'apt', 'deb']
      ansible.builtin.include_tasks: "slack/{{ ansible_facts['os_family'] }}.yml"

    - name: include flatpak installation tasks
      when: slack_installation_method == 'flatpak'
      ansible.builtin.import_tasks: slack/flatpak.yml

- name: configure zoom
  when: "'zoom' in communication_clients"
  tags:
    - zoom
  ansible.builtin.include_role:
    name: gotmax23.zoom
    apply:
      become: true
