---
- name: configure discord
  include: discord.yml
  tags:
  - discord

- name: configure signal
  include_role:
    name: staticdev.signal
  tags:
  - signal

- name: configure slack
  include: slack.yml
  tags:
  - slack

- name: configure zoom
  become: yes
  include: zoom.yml
  tags:
  - zoom
