---
- name: configure discord
  import_tasks: discord.yml
  tags:
  - discord

- name: configure signal
  ansible.builtin.include_role:
    name: staticdev.signal
  tags:
  - signal

- name: configure slack
  import_tasks: slack.yml
  tags:
  - slack

- name: configure zoom
  become: true
  import_tasks: zoom.yml
  tags:
  - zoom
