# TODO: Do not hardcode x64
---
- name: install slack
  become: true
  ansible.builtin.apt:
    deb: https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-{{ slack_machine_map[ansible_machine] }}.deb # noqa line-length
  when: ('slack-desktop' not in ansible_facts.packages) or
        (slack_version not in ansible_facts.packages['slack-desktop'] | map(attribute='version'))
