---
- name: get path of armored slack signing key
  ansible.builtin.set_fact:
    slack_signing_key: "{{ lookup('fileglob', 'slack.key') }}" # from /etc/cron.daily/slack

- name: add slack signing key to apt
  become: true
  ansible.builtin.shell:
    cmd: gpg --dearmor < "{{ slack_signing_key }}" > /etc/apt/trusted.gpg.d/packagecloud.io-slack.gpg
    creates: /etc/apt/trusted.gpg.d/packagecloud.io-slack.gpg
  changed_when: false

- name: add apt slack.list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    filename: slack
    state: present
    update_cache: true

- name: install slack-desktop
  become: true
  ansible.builtin.apt:
    name: slack-desktop
    state: latest
