---
- name: enable i386 architecture with dpkg
  ansible.builtin.lineinfile:
    path: /var/lib/dpkg/arch
    line: 'i386'
    create: yes
    mode: 0644
  register: add_i386

# Need to try on a new system, this might be hung up on a license agreement
- name: install steam
  become: yes
  ansible.builtin.apt:
    name: steam
    update_cache: '{{ add_i386.changed }}'
