---
# Like everything else this is pretty Fedora-specific, refer to
# https://packagecloud.io/slacktechnologies/slack/install#manual-rpm
# if using some other RPM-based setup

- name: get path of armored slack signing key
  ansible.builtin.set_fact:
    slack_signing_key: "{{ lookup('fileglob', 'slack.key') }}" # https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: import slack signing key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "{{ slack_signing_key }}"

# copy instead of yum_repository as the daily cronjob will just overwrite
- name: add yum slack.repo
  become: true
  ansible.builtin.copy:
    src: slack.repo
    dest: /etc/yum.repos.d/slack.repo
    owner: root
    group: root
    mode: 0644
    force: false

- name: install slack
  become: true
  ansible.builtin.package:
    name: slack
    state: latest
    enablerepo: slacktechnologies_slack
