---
- name: ansible_user
  set_fact:
    ansible_user: "{{ lookup('env', 'USER') | default('ben', true) }}"
  tags:
  - always
  - ansible_user

- name: configure terminal
  include: terminal.yml
  tags: terminal
