---
- name: configure shells
  import_tasks: shells.yml
  tags: shells

- name: configure git
  import_tasks: git.yml
  tags:
    - git

- name: configure asdf
  import_tasks: asdf.yml
  tags:
    - asdf

- name: download complete-alias
  ansible.builtin.git:
    repo: git@github.com:cykerway/complete-alias.git
    dest: "{{ ansible_user_dir }}/.complete-alias"
    version: "{{ complete_alias_version }}"
  when:
    - configure_complete_alias
  tags:
    - complete-alias

- name: install common terminal apps
  become: true
  ansible.builtin.apt:
    name: "{{ common_terminal_packages | union(additional_terminal_packages | default([])) | unique }}"
    state: latest
  tags:
    - apt

- name: install bat
  ansible.builtin.include_role:
    name: gantsign.bat

- name: install yq
  ansible.builtin.include_role:
    name: andrewrothstein.yq
