---
- name: ansible_user
  ansible.builtin.set_fact:
    ansible_user: "{{ lookup('env', 'USER') | default('ben', true) }}"
  tags:
    - always
    - ansible_user

- name: configure terminal
  import_tasks: terminal.yml
  tags: terminal

- name: configure common dev tools
  import_tasks: dev_tools.yml
  tags:
    - terminal
    - dev
