---
- name: gather current package facts
  ansible.builtin.package_facts:
    manager: auto
  tags:
    - always

- name: configure terminal
  import_tasks: terminal.yml
  tags: terminal

- name: configure common dev tools
  import_tasks: dev_tools.yml
  tags:
    - terminal
    - dev
