---
# NO, put this in bash files
# - name: asdfkasdlf;sajdfasdkl;jf
#   copy:
#   content: |
#     # Managed by Ansible
#     [[ ":$PATH:" != *"${HOME}/.local/bin"* ]] && PATH="${HOME}/.local/bin:${PATH}"
#   dest: /etc/profile.d/asdfqwerg
#   owner: root
#   group: root
#   mode: '0644'

- name: install common terminal apps
  become: true
  ansible.builtin.apt:
    name: "{{ common_terminal_packages | union(additional_terminal_packages | default([])) | unique }}"
    state: latest
  tags:
    - apt

- name: install bat
  ansible.builtin.include_role:
    name: gantsign.bat

- name: install yq
  ansible.builtin.include_role:
    name: andrewrothstein.yq

- name: configure terminal
  ansible.builtin.template:
    src: "home/{{ item }}"
    dest: "/home/{{ ansible_user }}/.{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items: [ ]
  # - bash_profile
  # - bashrc
  # - inputrc
  # - profile
  tags:
    - terminal
    - bashrc
