---
# Reminder: pair devices manually, at least for now

- name: include os_family-specific solaar pre-tasks
  ansible.builtin.include_tasks: "solaar-{{ ansible_facts['os_family'] }}.yml"

- name: Install solaar
  become: true
  ansible.builtin.package:
    name: solaar
    state: latest
    update_cache: true

- name: Populate solaar rules scripts
  ansible.builtin.copy:
    src: "solaar/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    mode: 0775
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  loop: "{{ solaar_rules | selectattr('script', 'defined') | map(attribute='script') }}"
  when: solaar_rules is defined

- name: Populate solaar rules
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.config/solaar/rules.yaml"
    marker: "# {mark} ANSIBLE MANAGED RULE {{ item.key }}: {{ item.key_action }}"
    create: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664
    block: |
      ---
      - Key: [{{ item.key }}, pressed]
      - Execute: {{ item.key_action }}
      ...
  with_items: "{{ solaar_rules }}"
  when: solaar_rules is defined
