---
additional_terminal_packages:
  - lshw
  - powertop
  - python3-dnf-plugin-tracer

configure_container_management: true
container_engine: podman

additional_gui_packages:
  - btrfs-assistant
  - dconf-editor
  - filezilla
  - gnome-boxes
  - igt-gpu-tools
  - shotwell
gui_packages_removal:
  - abrt
  - gnome-maps
  - libreoffice-*

configure_virtualization: true
# hashicorp's repo does not support F37 yet
# curl https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml to test
configure_vagrant: false

configure_vscode: true
